// Constantes centralizadas de la aplicación para eliminar duplicación.
class AppConstants {
  AppConstants._(); // Prevenir instanciación

  /// Departamentos de Honduras para selección de ubicación.
  static const List<String> departments = [
    'Atlántida',
    'Choluteca',
    'Colón',
    'Comayagua',
    'Copán',
    'Cortés',
    'El Paraíso',
    'Francisco Morazán',
    'Gracias a Dios',
    'Intibucá',
    'Islas de la Bahía',
    'La Paz',
    'Lempira',
    'Ocotepeque',
    'Olancho',
    'Santa Bárbara',
    'Valle',
    'Yoro',
  ];

  /// Municipios de Honduras organizados por departamento.
  static const Map<String, List<String>> municipalitiesByDepartment = {
    'Atlántida': [
      'La Ceiba',
      'El Porvenir',
      'Jutiapa',
      'La Masica',
      'San Francisco',
      'Tela',
      'Arizona',
      'Esparta',
    ],
    'Choluteca': [
      'Choluteca',
      'Apacilagua',
      'Concepción de María',
      'Duyure',
      'El Corpus',
      'El Triunfo',
      'Marcovia',
      'Morolica',
      'Namasigue',
      'Pespire',
      'San Antonio de Flores',
      'San Isidro',
      'San José',
      'Santa Ana de Yusguare',
    ],
    'Colón': [
      'Trujillo',
      'Balfate',
      'Iriona',
      'Limón',
      'Sabá',
      'Santa Fe',
      'Santa Rosa de Aguán',
      'Sonaguera',
      'Tocoa',
      'Bonito Oriental',
    ],
    'Comayagua': [
      'Comayagua',
      'Ajuterique',
      'El Rosario',
      'Esquipulas del Norte',
      'Humuya',
      'La Libertad',
      'Lamaní',
      'Maraita',
      'Meámbar',
      'Minas de Oro',
      'Ojos de Agua',
      'San Jerónimo',
      'San José de Comayagua',
      'San Sebastián',
      'Siguatepeque',
      'Villa de San Antonio',
    ],
    'Copán': [
      'Santa Rosa de Copán',
      'Cabañas',
      'Concepción',
      'Copán Ruinas',
      'Corquín',
      'Cucuyagua',
      'Dolores',
      'Dulce Nombre',
      'El Paraíso',
      'Florida',
      'La Jigua',
      'La Unión',
      'Nueva Arcadia',
      'San Agustín',
      'San Antonio',
      'San Jerónimo',
      'San José',
      'San Nicolás',
      'Santa Rita',
      'Trinidad de Copán',
      'Veracruz',
    ],
    'Cortés': [
      'San Pedro Sula',
      'Choloma',
      'La Lima',
      'Omoa',
      'Puerto Cortés',
      'Pimienta',
      'Potrerillos',
      'San Antonio de Cortés',
      'San Francisco de Yojoa',
      'San Manuel',
      'Santa Cruz de Yojoa',
      'Villanueva',
      'Jesús de Otoro',
    ],
    'El Paraíso': [
      'Yuscarán',
      'Alauca',
      'Danlí',
      'El Paraíso',
      'Güinope',
      'Jacaleapa',
      'Liure',
      'Morocelí',
      'Orica',
      'Potrerillos',
      'San Antonio de Flores',
      'San Lucas',
      'San Matías',
      'Soledad',
      'Teupasenti',
      'Trojes',
      'Vado Ancho',
      'Yauyupe',
    ],
    'Francisco Morazán': [
      'Tegucigalpa',
      'Alubarén',
      'Cedros',
      'Curarén',
      'El Porvenir',
      'Guaimaca',
      'La Libertad',
      'La Venta',
      'Marale',
      'Maraita',
      'Ojojona',
      'Orica',
      'Reitoca',
      'Sabanagrande',
      'San Antonio de Oriente',
      'San Buenaventura',
      'San Ignacio',
      'Santa Ana',
      'Talanga',
      'Tatumbla',
      'Valle de Ángeles',
      'Villa de San Francisco',
      'Villa Guadalupe',
      'Yangüela',
    ],
    'Gracias a Dios': [
      'Puerto Lempira',
      'Brus Laguna',
      'Ahuas',
      'Juan Francisco Bulnes',
      'Ramón Villeda Morales',
      'Wampusirpi',
    ],
    'Intibucá': [
      'La Esperanza',
      'Camasca',
      'Colomoncagua',
      'Concepción',
      'Dolores',
      'Intibucá',
      'Jesús de Otoro',
      'Magdalena',
      'San Antonio',
      'San Isidro',
      'San Juan',
      'Santa Lucía',
      'Yamaranguila',
      'San Marco de Sierra',
    ],
    'Islas de la Bahía': ['Roatán', 'Guanaja', 'Utila'],
    'La Paz': [
      'La Paz',
      'Aguanqueterique',
      'Cabañas',
      'Cane',
      'Chinacla',
      'Guajiquiro',
      'Lauterique',
      'Marcala',
      'Mercedes de Oriente',
      'Oropolí',
      'San Antonio del Norte',
      'San José',
      'Santa Elena',
      'Santa María',
      'Seren',
    ],
    'Lempira': [
      'Gracias',
      'Belen Gualcho',
      'Candelaria',
      'Cololaca',
      'Erandique',
      'Gualcince',
      'Guarita',
      'La Campa',
      'La Iguala',
      'Las Flores',
      'La Virtud',
      'Piraera',
      'San Andrés',
      'San Francisco',
      'San Juan Guarita',
      'San Sebastián',
      'Santa Cruz',
      'Talgua',
      'Tambla',
      'Tomalá',
      'Valladolid',
      'Virginia',
    ],
    'Ocotepeque': [
      'Ocotepeque',
      'Belén Gualcho',
      'Concepción',
      'Fraternidad',
      'La Encarnación',
      'La Labor',
      'Lucerna',
      'Mercedes',
      'San Fernando',
      'San Francisco del Valle',
      'San Jorge',
      'San Marcos',
      'Santa Fé',
      'Sensenti',
      'Sinuapa',
    ],
    'Olancho': [
      'Juticalpa',
      'Campamento',
      'Catacamas',
      'Concordia',
      'Dulce Nombre de Culmí',
      'El Rosario',
      'Guata',
      'Guayape',
      'Jano',
      'La Unión',
      'Mangulile',
      'Manto',
      'Salamá',
      'San Esteban',
      'San Francisco de Becerra',
      'Santa María del Real',
      'Silca',
      'Yocón',
      'Patuca',
    ],
    'Santa Bárbara': [
      'Santa Bárbara',
      'Arada',
      'Atima',
      'Azacualpa',
      'Ceguaca',
      'Chinda',
      'Concepción del Norte',
      'El Níspero',
      'Gualala',
      'Ilama',
      'Las Vegas',
      'Macuelizo',
      'Naranjito',
      'Petoa',
      'Protección',
      'Quimistán',
      'San Francisco de Ojuera',
      'San José de Colinas',
      'San Luis',
      'San Nicolás',
      'Santa Rita',
      'Trinidad',
    ],
    'Valle': [
      'Nacaome',
      'Alianza',
      'Amapala',
      'Aramecina',
      'Caridad',
      'Goascorán',
      'Langue',
      'San Francisco de Coray',
      'San Lorenzo',
      'Yarumela',
    ],
    'Yoro': [
      'Yoro',
      'Arenal',
      'El Negrito',
      'El Progreso',
      'Jocón',
      'Morazán',
      'Olanchito',
      'Santa Rita',
      'Sulaco',
      'Victoria',
      'Yorito',
    ],
  };

  /// Tipos de propiedad soportados.
  static const List<String> propertyTypes = [
    'Casa',
    'Apartamento',
    'Terreno',
    'Edificio Comercial',
    'Local',
    'Oficina',
    'Otro',
  ];
}
